name: RealWinter
main: org.creezo.realwinter.RealWinter
version: 1.1.6
author: creezo
softdepent: [Multiverse-Core]

commands: 
  rw:
    description: 'Basic player commands.'
    permission: realwinter.player
    permission-message: 'You dont have permission - realwinter.player'
    usage: 'Usage: /rw <command>'
  rwadmin:
    description: 'Administration commands.'
    permission: realwinter.admin
    permission-message: 'You dont have permission - realwinter.admin'
    usage: 'Usage: /rwadmin <command>'

permissions:
  realwinter.*:
    description: 'Gives you all permissions. Including immune!'
    children:
        realwinter.admin: true
        realwinter.player: true
  realwinter.player:
    description: 'Grants ability to use RealWinter player informative commands.'
    default: op
  realwinter.admin:
    description: 'Grants ability to use RealWinter admin commands.'
    default: op
  realwinter.immune:
    description: 'Makes player immune to all RW effects.'
    default: false
  realwinter.immune.winter:
    description: 'Makes player immune to freezing.'
    default: false
  realwinter.immune.desert:
    description: 'Makes player immune exhausting in desert.'
    default: false
  realwinter.immune.thirst:
    description: 'Makes player immune to global thirst.'
    default: false
  realwinter.immune.jungle:
    description: 'Makes player immune to jungle insect.'
    default: false