name: RealWinter
main: org.creezo.realwinter.RealWinter
version: 1.1.3
author: creezo

commands: 
  realwinter:
    aliases: rw
    permission: realwinter.command

permissions:
  realwinter.*:
    description: Access to RealWinter.
    children:
      realwinter.command: true
  realwinter.command:
    description: Grants ability to use RealWinter commands.
    default: op