name: RealWinter
main: org.creezo.realwinter.RealWinter
version: 1.1.4
author: creezo

commands: 
  rw:
    permission: realwinter.player
  rwadmin:
    permission: realwinter.admin

permissions:
  realwinter.*:
    description: Gives you all permissions.
    children:
        realwinter.admin: true
        realwinter.player: true
  realwinter.player:
    description: Grants ability to use RealWinter player informative commands.
    default: true
  realwinter.admin:
    description: Grants ability to use RealWinter admin commands.
    default: op
  realwinter.immune:
    description: Makes player immune to all RW effects.
    default: false
  realwinter.immune.winter:
    description: Makes player immune to freezing.
    default: true
  realwinter.immune.desert:
    description: Makes player immune exhausting in desert.
    default: true
