name: RealWeather
main: org.creezo.realweather.RealWeather
version: 1.7.2
author: creezo
#depend: [PlayerSpeedAPI]
softdepend: [Multiverse-Core, ProtocolLib, PlayerSpeedAPI]
description: 'Makes the weather more dangerous by extending its effects.'
website: http://dev.bukkit.org/server-mods/realwinter/
dev-url: http://dev.bukkit.org/server-mods/realwinter/

commands: 
  rw:
    description: 'RealWeather basic player commands.'
    permission: realweather.player
    permission-message: 'You dont have permission - realweather.player'
    usage: 'Usage: /rw <command>'
  rwadmin:
    description: 'RealWeather administration commands.'
    permission: realweather.admin
    permission-message: 'You dont have permission - realweather.admin'
    usage: 'Usage: /rwadmin <command>'

permissions:
  realweather.*:
    description: 'Gives you all permissions. (Maybe) Including immune!'
    children:
        realweather.admin: true
        realweather.player: true
  realweather.player:
    description: 'Grants ability to use RealWeather player informative commands.'
    default: true
  realweather.admin:
    description: 'Grants ability to use RealWeather admin commands.'
    default: op
  realweather.immune.all:
    description: 'Makes player immune to all RW effects.'
    default: false
  realweather.immune.winter:
    description: 'Makes player immune to freezing.'
    default: false
  realweather.immune.desert:
    description: 'Makes player immune exhausting in desert.'
    default: false
  realweather.immune.thirst:
    description: 'Makes player immune to global thirst.'
    default: false
  realweather.immune.jungle:
    description: 'Makes player immune to jungle insect.'
    default: false